version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.6.0
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package.json" }}
      - run:
          command: |
            yarn install
      - save_cache:
          key: v1-deps-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run:
          command: |
            ./node_modules/.bin/gulp lint
