version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          command: |
            npm i
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          command: |
            npm run build && npm run babel
  test:
    docker:
      - image: cimg/node:16.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          command: |
            npm i
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"
      - run:
          command: |
            npm run test
