version: 2

# Variables
node: &node
  image: cimg/node:16.13

npm_restore_cache: &npm_restore_cache
  restore_cache:
    keys:
      - v1-deps-{{ checksum "package-lock.json" }}
      - v1-deps-

npm_install: &npm_install
  run:
    command: npm i

npm_save_cache: &npm_save_cache
  save_cache:
    key: v1-deps-{{ checksum "package-lock.json" }}
    paths:
      - "node_modules"

# Jobs
jobs:
  build:
    docker:
      - *node
    steps:
      - checkout
      - *npm_restore_cache
      - *npm_install
      - *npm_save_cache
      - run:
          command: npm run build:all
  test:
    docker:
      - *node
    steps:
      - checkout
      - *npm_restore_cache
      - *npm_install
      - *npm_save_cache
      - run:
          command: npm run test
  build-storybook:
    docker:
      - *node
    steps:
      - checkout
      - *npm_restore_cache
      - *npm_install
      - *npm_save_cache
      - run:
          command: npm run storybook:build

# Workflows
workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build
      - build-storybook
